version: "3.8"

services:
  app:
    env_file: ".env"
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "${SERVER_PORT}:8080"
    volumes:
      - ./:/app
      - /app/tmp
    command: ["air"]
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro # Include Nginx configuration
    depends_on:
      - app

volumes:
  postgres_data:
